### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by Pokecub573** [jiqizhixin/Artificial-Intelligence-Terminology#1]
其实可以建一个项目专门的 Github Page .
这样查阅感觉有点不便。

**Comment by Horatio-JSY** [comment]
好啊，我们会尝试使用Github Page的

**Comment by Horatio-JSY** [comment]
Github Page：https://jiqizhixin.github.io/AI-Terminology-page/

**Comment by mymartin** [comment]
为什么不把 Page 页面的链接写在描述里呢。
